---
deployment:
  # Ensure this file is named exactly “.cpanel.yml” in the repo root
  tasks:
    # Install everything, including devDependencies (so patch-package is available)
    - npm install
    # Build your Next.js app (or your custom build step)
    - npm run build
    # Restart or start your app (adjust to your startup process)
    - pm2 restart all --update-env
